### ISSUE TITLE
Microsoft Defender is flagging this as a trojan

### ISSUE THREAD

**Issue by iterating** [ABS96/coloured-folders#1]
Microsoft Defender is flagging this as a trojan.
![image](https://user-images.githubusercontent.com/6834401/95060919-c3dcc100-06af-11eb-823d-1f657325bdfa.png)

**Comment by ABS96** [comment]
Thanks for reporting.

Looks like Microsoft Defender has a tendency to interpret AutoHotKey based programs as trojans.

My guess for what causes this:

- the program checks the version of Windows
- the binaries are not signed

I've ran the latest release by [VirusTotal](https://www.virustotal.com/gui/file/0562dbdedd4451b91a28a76e27bb1711d6e814f76ae6e55cfe5a39215027e208/detection), just in case. Other engines are also detecting false positives.

I'll need to look into this.

**Comment by ABS96** [comment]
Microsoft Defender doesn't see the latest version as a threat (on my machine at least), so I'm closing the ticket.
If the problem resurfaces, it can be reopened.

**Comment by ABS96** [comment]
Microsoft Defender doesn't see the latest version as a threat (on my machine at least), so I'm closing the ticket.
If the problem resurfaces, it can be reopened.
