### ISSUE TITLE
Some icons don't work correctly

### ISSUE THREAD

**Issue by kiwichick888** [ABS96/coloured-folders#2]
EDITED TO ADD: I just downloaded the icon pack you uploaded to Deviant Art (https://www.deviantart.com/abs96/art/Windows-10-coloured-folder-icons-661291513) and all of those icons are fine.

I realise the latest version is over 3 years old but I don't see how that could have an affect with this issue. Some of the icons don't work properly (102 & 105-110). When applied to a folder or extracted from the icons.dll file, they don't look the way they should. Checking the contents of the icon files shows they all contain the same number of icon images, the same sizes, in the same order but something is wrong with some of them. I tried saving just the 256x256 icon image as a png and created a new icon from that but the problem still exists which I find to be very strange.

Icons extracted from icons.dll
![icons extracted from icons dll](https://github.com/ABS96/coloured-folders/assets/6602525/60411e3a-5e4a-4346-9659-7a95e3b397a6)

Icons applied to folders
![icons applied to folders](https://github.com/ABS96/coloured-folders/assets/6602525/6941329a-aad1-41d7-89b1-61cb5a00a96d)

**Comment by ABS96** [comment]
I can confirm the issue. I've made an icon library which doesn't seem to have this issue, so if you're using the icons natively without my picker, this might be more convenient:
[coloured_folders_icl.zip](https://github.com/ABS96/coloured-folders/files/12041155/coloured_folders_icl.zip)

**Comment by kiwichick888** [comment]
> I can confirm the issue. I've made an icon library which doesn't seem to have this issue, so if you're using the icons natively without my picker, this might be more convenient: [coloured_folders_icl.zip](https://github.com/ABS96/coloured-folders/files/12041155/coloured_folders_icl.zip)

Thanks, that's much better. Any chance you'll update your picker to include the new icons?

**Comment by ABS96** [comment]
Thanks for the feedback.
Yes, now that I see that there's still interest for the program, I'm planning to update it.

**Comment by kiwichick888** [comment]
> Thanks for the feedback. Yes, now that I see that there's still interest for the program, I'm planning to update it.

Thank you! 🙂

**Comment by ABS96** [comment]
I've released a new version. Could you confirm that it fixes the problem with the icons?

**Comment by kiwichick888** [comment]
> I've released a new version. Could you confirm that it fixes the problem with the icons?

I installed the new version, applied the colour of one of the previous problematic icons and it worked perfectly! Thank you so much.

**Comment by ABS96** [comment]
You're welcome, I'm glad we managed to sort this out 🙂
